// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFLzqYXGFDBnxhlHAfQaY4xGk3WmNRJE',
    appId: '1:9736194075:web:4eb3ef40f0402812d550be',
    messagingSenderId: '9736194075',
    projectId: 'quickrecipe-00',
    authDomain: 'quickrecipe-00.firebaseapp.com',
    storageBucket: 'quickrecipe-00.firebasestorage.app',
    measurementId: 'G-6VSZ4XW5HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzMoDnVYbjp3etQkw9ARIRLXrD2tE430U',
    appId: '1:9736194075:android:e6c9295bf7558228d550be',
    messagingSenderId: '9736194075',
    projectId: 'quickrecipe-00',
    storageBucket: 'quickrecipe-00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgzcNPQ_AatFNrwxWvIbjvKdpiIvGM1c',
    appId: '1:9736194075:ios:f6c4ebe533138d58d550be',
    messagingSenderId: '9736194075',
    projectId: 'quickrecipe-00',
    storageBucket: 'quickrecipe-00.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgzcNPQ_AatFNrwxWvIbjvKdpiIvGM1c',
    appId: '1:9736194075:ios:f6c4ebe533138d58d550be',
    messagingSenderId: '9736194075',
    projectId: 'quickrecipe-00',
    storageBucket: 'quickrecipe-00.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAFLzqYXGFDBnxhlHAfQaY4xGk3WmNRJE',
    appId: '1:9736194075:web:ad536f00c159c5d4d550be',
    messagingSenderId: '9736194075',
    projectId: 'quickrecipe-00',
    authDomain: 'quickrecipe-00.firebaseapp.com',
    storageBucket: 'quickrecipe-00.firebasestorage.app',
    measurementId: 'G-278BMSP4BL',
  );
}
